### PR TITLE
zset-ziplist-to-memkind

### PR DESCRIPTION
**Pull request by TomekIdczak97**
zset ziplist moved to memkind

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/46)

### CODE REVIEW

**Comment by KFilipek** [comment]
Please change commit message

**Comment by KFilipek** [comment]
Only one insignificant change, can be changed on another PR.

---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/object.c, line 328 at r1](https://reviewable.io/reviews/pmem/redis/46#-LDBHxnH3H6EfLAAchbw:-LDBHxnI6VxNnBh-o6J1:b-u0vurp) ([raw file](https://github.com/pmem/redis/blob/97827ecd7877397ee4633d435f551da345d53a7b/src/object.c#L328)):*
> ```C
>         }
>         if(o->encoding == OBJ_ENCODING_EMBSTR || o->encoding == OBJ_ENCODING_INT
>         		|| o->encoding == OBJ_ENCODING_ZIPLIST || o->encoding == OBJ_ENCODING_SKIPLIST)
> ```

Tabs instead of spaces

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46#-:-LDHJe013c7oIw-Y47hy:b-vryzlk)*

**Comment by KFilipek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46#-:-LDHJyMzCCe4Nt7Ff1HW:bnfp4nl)*

**Comment by KFilipek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/object.c, line 229 at r2](https://reviewable.io/reviews/pmem/redis/46#-LDHQ7OpEEMFeMBceuA-:-LDHQ7OpEEMFeMBceuA0:b15yrjm) ([raw file](https://github.com/pmem/redis/blob/c5e250e75d74db3ba24ccdd170df00e617008c4c/src/object.c#L229)):*
> ```C
>     zs->dict = dictCreate(&zsetDictType,NULL);
>     zs->zsl = zslCreate();
>     o = createObjectA(OBJ_ZSET,zs,a);
> ```

We should contain only data in PM, not robj's.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46)*

**Comment by KFilipek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/object.c, line 328 at r2](https://reviewable.io/reviews/pmem/redis/46#-LDHUgGG8U8UmCEjqoEk:-LDHUgGG8U8UmCEjqoEl:b-xup0r4) ([raw file](https://github.com/pmem/redis/blob/c5e250e75d74db3ba24ccdd170df00e617008c4c/src/object.c#L328)):*
> ```C
>         }
>         if(o->encoding == OBJ_ENCODING_EMBSTR || o->encoding == OBJ_ENCODING_INT
>         		|| o->encoding == OBJ_ENCODING_ZIPLIST || o->encoding == OBJ_ENCODING_SKIPLIST)
> ```

Also freeing robj should be done by zfree instead of memkind

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46)*

**Comment by KFilipek** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/t_zset.c, line 2011 at r5](https://reviewable.io/reviews/pmem/redis/46#-LD_wozIAQLfD3ilmlyb:-LD_wozIAQLfD3ilmlyc:bvvioax) ([raw file](https://github.com/pmem/redis/blob/93138f7323198808ba5a48976b115b346e56ddaf/src/t_zset.c#L2011)):*
> ```C
>         return ele;
>     } else if (val->ele) {
>         return sdsdup(val->ele);
> ```

sdsdup also allocate memory

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46)*

**Comment by kasiawasiuta** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/object.c, line 88 at r4](https://reviewable.io/reviews/pmem/redis/46#-LDf3sIRCz2vzVr4itSF:-LDf3sIRCz2vzVr4itSG:bax48lu) ([raw file](https://github.com/pmem/redis/blob/718a924c73571fbc12e58188071547d2a74b1ff2/src/object.c#L88)):*
> ```C
>  * allocated in the same chunk as the object itself. */
> robj *createEmbeddedStringObjectA(const char *ptr, size_t len, alloc a) {
>     //robj *o = a->alloc(sizeof(robj)+sizeof(struct sdshdr8)+len+1);
> ```

pls remove

---

*[src/server.h, line 1518 at r4](https://reviewable.io/reviews/pmem/redis/46#-LDf5X5g-unXqHbcNkYb:-LDf5X5g-unXqHbcNkYc:bki07fj) ([raw file](https://github.com/pmem/redis/blob/718a924c73571fbc12e58188071547d2a74b1ff2/src/server.h#L1518)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> static inline robj *createSetObject(void){return createSetObjectA(z_alloc);}
> static inline robj *createSetObjectM(void){return createSetObjectA(m_alloc);}
> robj *createIntsetObject(void);
> robj *createZsetObjectA(alloc a);
> static inline robj *createZsetObject(void){return createZsetObjectA(z_alloc);}
> static inline robj *createZsetObjectM(void){return createZsetObjectA(m_alloc);}
> robj *createZsetZiplistObjectA(alloc a);
> static inline robj *createZsetZiplistObject(void){return createZsetZiplistObjectA(z_alloc);}
> static inline robj *createZsetZiplistObjectM(void){return createZsetZiplistObjectA(m_alloc);}
> robj *createHashObjectA(alloc a);
> ```
</details>

add whitespaces

---

*[src/server.h, line 1650 at r4](https://reviewable.io/reviews/pmem/redis/46#-LDf5imSEYcKJCmjo7Xd:-LDf5imSEYcKJCmjo7Xe:bhh06pp) ([raw file](https://github.com/pmem/redis/blob/718a924c73571fbc12e58188071547d2a74b1ff2/src/server.h#L1650)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> atic inline int zsetAdd(robj *zobj, double score, sds ele, int *flags, double *newscore){return zsetAddA(zobj,score,ele,flags,newscore,z_alloc);}
> static inline int zsetAddM(robj *zobj, double score, sds ele, int *flags, double *newscore){return zsetAddA(zobj,score,ele,flags,newscore,m_alloc);}
> long zsetRank(robj *zobj, sds ele, int reverse);
> int zsetDelA(robj *zobj, sds ele, alloc a);
> static inline int zsetDel(robj *zobj, sds ele){return zsetDelA(zobj,ele,z_alloc);}
> ```
</details>

ditto

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46)*

**Comment by karpiop** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/46#-:-LDg4ZzdDE8nBWbKRuAV:bnfp4nl)*

**Pull request merged**
