### PR TITLE
Update README with KMEM DAX informations

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/186)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/186)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg, @kasiawasiuta, and @michalbiesek)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/redis/186#-M7Mp46mDxCZnIEN98mD:-M7Mp46mDxCZnIEN98mE:b15oflu) ([raw file](https://github.com/pmem/redis/blob/8aea5e8a4a43699ef13ac31ef64dcac364bbd72c/README.md#L1)):*
> ```Markdown
> This is README for Redis adjusted to store objects on both DRAM and Intel Optane Persistent Memory.
> ```

nit: 'This README is' sounds better.
___
*[README.md, line 28 at r1](https://reviewable.io/reviews/pmem/redis/186#-M7MocOpDlQ_RdVmISyB:-M7MocOpDlQ_RdVmISyC:bu0il6s) ([raw file](https://github.com/pmem/redis/blob/8aea5e8a4a43699ef13ac31ef64dcac364bbd72c/README.md#L28)):*
> ```Markdown
> --------------
> You will need to install the following required packages on the build system:
> * libmemkind
> ```

The package name on Fedora is either memkind or memkind-devel

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/186)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jschmieg, @kasiawasiuta, and @PatKamin)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aMaJsAPJPWDvZGXy2:-M7aMaJsAPJPWDvZGXy3:b-4cf11m) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L3)):*
> ```
> System RAM
> ```
system-ram
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aN3VmACOE9Ds7JePi:-M7aN3VmACOE9Ds7JePj:bq68lfj) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L3)):*
> ```
> Intel Optane Persistent Memory
> ```
 Intel Optane Persistent Memory (PMEM)

and later refer only to PMEM ?
___
*[README.md, line 28 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aLNW1E7PFeGr5ecRy:-M7aLNW1E7PFeGr5ecRz:buin9z8) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L28)):*
> ```
> * memkind
> ```
You don't want to version memkind here ? v1.10.0/ v1.10.1 rc1/ since some commit from master ? You want to have this dependency as needed to work or the one which we use ?

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/186)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jschmieg, @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aMaJsAPJPWDvZGXy2:-M7h0BcxDDBEbOIVE3b8:b-896fix) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L3)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> System RAM
> ```
system-ram
</blockquote></details>

Done.
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aN3VmACOE9Ds7JePi:-M7h0CPo3LVNA9npChvC:b-896fix) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L3)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Intel Optane Persistent Memory
> ```
 Intel Optane Persistent Memory (PMEM)

and later refer only to PMEM ?
</blockquote></details>

Done.
___
*[README.md, line 28 at r2](https://reviewable.io/reviews/pmem/redis/186#-M7aLNW1E7PFeGr5ecRy:-M7h0DnDAdns0FQb78id:brbbwe5) ([raw file](https://github.com/pmem/redis/blob/ef95f79e0a2f09d39e0730208deb5ffc55ef82fc/README.md#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> * memkind
> ```
You don't want to version memkind here ? v1.10.0/ v1.10.1 rc1/ since some commit from master ? You want to have this dependency as needed to work or the one which we use ?
</blockquote></details>

I will add this after memkind final release.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/186)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jschmieg, @kasiawasiuta, and @PatKamin)

**Pull request merged**
