### PR TITLE
4.0 volatile hashtable

### PR DESCRIPTION
**Pull request by KFilipek**
Work in progress, reviews are welcome.
Tests are passing at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/24)

### CODE REVIEW

**Comment by karpiop** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/bitops.c, line 493 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmjO2w0T40Oa_XHUFN:-LAmjO2w0T40Oa_XHUFO:bx237z) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L493)):*
> ```C
> }
> 
> robj *lookupStringForBitCommandM(client *c, size_t maxbit) {
> ```

redundant code, should be parametrized

---

*[src/bitops.c, line 498 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmTDnDC2Ja2gBXiEYJ:-LAmTDnDC2Ja2gBXiEYK:b-odlgvb) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L498)):*
> ```C
> //    serverPanic("NOT IMPLEMENTED"); // TODO
>     if (o == NULL) {
>         o = createObject(OBJ_STRING,sdsnewlenM(NULL, byte+1));
> ```

you need to set allocator in robj *o

---

*[src/db.c, line 185 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmixrZCWy1hoBNjFPT:-LAmixrZCWy1hoBNjFPU:b-575i8k) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L185)):*
> ```C
>  }
> 
> void dbAddM(redisDb *db, robj *key, robj *val) {
> ```

same as dbAdd gtfo

---

*[src/db.c, line 235 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAminjc2DeL_mvTA3GO:-LAminjc2DeL_mvTA3GP:b1e2rtx) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L235)):*
> ```C
> }
> 
> void setKeyM(redisDb *db, robj *key, robj *val) {
> ```

should be parametrized 

---

*[src/dict.c, line 275 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmhoSu5f0GcWRcu0yt:-LAmhoSu5f0GcWRcu0yu:b-u18dnu) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/dict.c#L275)):*
> ```C
> }
> 
> int dictAddM(dict *d, void *key, void *val)
> ```

both functions are the same gtfo

---

*[src/object.c, line 230 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmiOJZ10mVom0ylfmF:-LAmiOJZ10mVom0ylfmG:b6x2syj) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/object.c#L230)):*
> ```C
>     o->encoding = OBJ_ENCODING_ZIPLIST;
>     return o;
> }
> ```

should be parametrized

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/24)*

**Comment by karpiop** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/t_hash.c, line 277 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmlhML6NjknlTG63M-:-LAmlhML6NjknlTG63M0:b-o30ya1) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L277)):*
> ```C
> }
> 
> int hashTypeSetM(robj *o, sds field, sds value, int flags) {
> ```

code redundance

---

*[src/t_hash.c, line 531 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmllER2X6jclqh_cX4:-LAmllER2X6jclqh_cX5:b-kmvgo9) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L531)):*
> ```C
>     robj *o = lookupKeyWrite(c->db,key);
>     if (o == NULL) {
>         if (a == m_alloc) {
> ```

should use createHashObjectA

---

*[src/t_hash.c, line 564 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmlqzu3d9PPJD9W59b:-LAmlqzu3d9PPJD9W59c:b-u9p8mw) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L564)):*
> ```C
>             sds key, value;
> 
>             //key = hashTypeCurrentObjectNewSdsA(hi,OBJ_HASH_KEY, a);
> ```

remove comment

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/24)*

**Comment by karpiop** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/t_hash.c, line 575 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmn7LJ6HAeMmS8yIRA:-LAmn7LJ6HAeMmS8yIRB:b-u9p8mw) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L575)):*
> ```C
>         }
>         hashTypeReleaseIterator(hi);
>         //zfree(o->ptr);
> ```

remove comment

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/24)*

**Comment by KFilipek** [comment]
Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/bitops.c, line 493 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmjO2w0T40Oa_XHUFN:-LAoNjPvBodO1mFBhR18:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L493)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

redundant code, should be parametrized
</blockquote></details>

Done.

---

*[src/bitops.c, line 498 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmTDnDC2Ja2gBXiEYJ:-LAoNk1p4BJJCKtCfT4v:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L498)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

you need to set allocator in robj *o
</blockquote></details>

Done.

---

*[src/db.c, line 185 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmixrZCWy1hoBNjFPT:-LAoNkzd01e5922ACZFy:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L185)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

same as dbAdd gtfo
</blockquote></details>

Done.

---

*[src/db.c, line 235 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAminjc2DeL_mvTA3GO:-LAoNlxf7oEDFafzgQpg:b-am2rv6) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L235)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

should be parametrized 
</blockquote></details>

Done. Deleted.

---

*[src/dict.c, line 275 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmhoSu5f0GcWRcu0yt:-LAoOtxI63a137y9TAs1:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/dict.c#L275)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

both functions are the same gtfo
</blockquote></details>

Done.

---

*[src/object.c, line 230 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmiOJZ10mVom0ylfmF:-LAoRNKQ-_1ZArsFYWqI:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/object.c#L230)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

should be parametrized
</blockquote></details>

Done.

---

*[src/t_hash.c, line 277 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmlhML6NjknlTG63M-:-LAoXv1C9WQgYQypEABb:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L277)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

code redundance
</blockquote></details>

Done.

---

*[src/t_hash.c, line 531 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmllER2X6jclqh_cX4:-LAoXwpd81eQdHN9jNcL:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L531)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

should use createHashObjectA
</blockquote></details>

Done.

---

*[src/t_hash.c, line 564 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmlqzu3d9PPJD9W59b:-LAoYxlv4CX4QMGLhelz:b-yf6vjq) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L564)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done. I've also move field/key to memkind

---

*[src/t_hash.c, line 575 at r1](https://beta.reviewable.io/reviews/pmem/redis/24#-LAmn7LJ6HAeMmS8yIRA:-LAoZ3cbDegXT0wE4-Vj:b-896fix) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L575)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/24)*

**Comment by karpiop** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/24#-:-LAsN1zY5985eSLch9aK:bnfp4nl)*

**Comment by karpiop** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/24#-:-LCmlr3m-f3R4CXkwp3P:bnfp4nl)*

**Comment by KFilipek** [comment]
retest this please

**Comment by KFilipek** [comment]
retest this please

**Comment by karpiop** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/24#-:-LD76_Ks9T3Rx0bQwpRi:bnfp4nl)*

**Comment by karpiop** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/bitops.c, line 493 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmjO2w0T40Oa_XHUFN:-LD77-uCBNSXjelCRMbW:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L493)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/bitops.c, line 498 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmTDnDC2Ja2gBXiEYJ:-LD76nUo09qo47D4zo3Z:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L498)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/db.c, line 185 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmixrZCWy1hoBNjFPT:-LD76qmV-OprIBryc0S2:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L185)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/dict.c, line 275 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmhoSu5f0GcWRcu0yt:-LD76roz0X2r6Rtumx1p:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/dict.c#L275)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/object.c, line 230 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmiOJZ10mVom0ylfmF:-LD76t0l1JKb103akz9F:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/object.c#L230)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/t_hash.c, line 277 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmlhML6NjknlTG63M-:-LD76wnM-GR3NXIlFDfe:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L277)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---

*[src/t_hash.c, line 575 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmn7LJ6HAeMmS8yIRA:-LD76zdp0pWZy1_-ga1j:b4putsz) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L575)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:ok_hand: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/24)*

**Comment by karpiop** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/bitops.c, line 493 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmjO2w0T40Oa_XHUFN:-LD77Ty90B6CQLUZFtnu:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L493)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/bitops.c, line 498 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmTDnDC2Ja2gBXiEYJ:-LD77_n8A_FGi7QDDoHv:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/bitops.c#L498)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/db.c, line 185 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmixrZCWy1hoBNjFPT:-LD77b-Q3o629XupY4BH:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/db.c#L185)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/dict.c, line 275 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmhoSu5f0GcWRcu0yt:-LD77c5i7YQnn06aHGLU:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/dict.c#L275)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/object.c, line 230 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmiOJZ10mVom0ylfmF:-LD77fd27aemo-Bb6L89:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/object.c#L230)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/t_hash.c, line 277 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmlhML6NjknlTG63M-:-LD77hT9EJqmLUi_1lID:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L277)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---

*[src/t_hash.c, line 575 at r1](https://reviewable.io/reviews/pmem/redis/24#-LAmn7LJ6HAeMmS8yIRA:-LD77igA8Koepq003EvO:b32w0x) ([raw file](https://github.com/pmem/redis/blob/1d87119e32564d3118ced3de717e921c4523a39c/src/t_hash.c#L575)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

:ok_hand: 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/redis/24)*

**Pull request merged**
