### PR TITLE
Calculate memory used by Persistent Memory

### PR DESCRIPTION
**Pull request by michalbiesek**
- extend output from INFO command

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/131)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/131)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg, @karpiop, @kasiawasiuta, and @michalbiesek)

___
*[src/zmalloc.c, line 170 at r1](https://reviewable.io/reviews/pmem/redis/131#-M-JtKp43Oaoq3b2nlbn:-M-JtKp52GX_m-GPkT_U:bbsvn91) ([raw file](https://github.com/pmem/redis/blob/db8d8abf72cb23f332bcd1e578605d3db78c7f12/src/zmalloc.c#L170)):*
> ```C
> }
> #else
> static int zmalloc_is_PMEM(void * ptr) {
> ```

Function above has "pmem" instead of "PMEM". I suggest to use one style on whole file. e.g. realloc_* has capital letters as postfix, but update_zmalloc_pmem_xxx not.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/131)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jschmieg, @karpiop, @kasiawasiuta, and @KFilipek)

___
*[src/zmalloc.c, line 170 at r1](https://reviewable.io/reviews/pmem/redis/131#-M-JtKp43Oaoq3b2nlbn:-M-JypV66hZ9xoc9qz7F:b-896fix) ([raw file](https://github.com/pmem/redis/blob/db8d8abf72cb23f332bcd1e578605d3db78c7f12/src/zmalloc.c#L170)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Function above has "pmem" instead of "PMEM". I suggest to use one style on whole file. e.g. realloc_* has capital letters as postfix, but update_zmalloc_pmem_xxx not.
</blockquote></details>

Done.

**Review by jschmieg — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/131)* status: all files reviewed, 1 unresolved discussion (waiting on @karpiop, @kasiawasiuta, and @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karpiop and @kasiawasiuta)

**Pull request merged**
