### PR TITLE
Initialize memkind dependency

### PR DESCRIPTION
**Pull request by michalbiesek**
- Added memkind library version 1.8.0 to redis 
- Extended Redis Makefile to build memkind as dependency

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/81)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 481 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/81)* status: 2 of 481 files reviewed, all discussions resolved

**Review by kasiawasiuta — COMMENTED** [review]
> Reviewed 481 of 481 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/81)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kasiawasiuta — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/81#-:-LXJZZ218ZCnj2pzEAG0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 479 of 481 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/81#-:-LXTimUF4lI65dqmOsnt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
