### PR TITLE
Add Dockerfile for Fedora 31

### PR DESCRIPTION
**Pull request by PatKamin**
Add bash scripts and Dockerfile to run tests on Fedora 31 image.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/123)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[utils/docker/docker_run_test.sh, line 26 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvujV756FaYsInfv-_:-LzvujV85Ew5CxyzlqIT:b3ley04) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/docker_run_test.sh#L26)):*
> ```
> # docker_run_build.sh - is called inside a Docker container;
> # prepares and runs redis build for specified pull request number
> ```
nit:
docker_run_test.sh - is called inside a Docker container
run redis tests
___
*[utils/docker/run_local.sh, line 27 at r1](https://reviewable.io/reviews/pmem/redis/123#-Lzvvi8f-56Ax83OpbXz:-Lzvvi8f-56Ax83OpbY-:bo20wrj) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L27)):*
> ```
> docker_run_build.sh
> ```
docker_run_test.sh
___
*[utils/docker/run_local.sh, line 46 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvvtptEb1BPoiCKFNo:-LzvvtptEb1BPoiCKFNp:b4wkucb) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L46)):*
> ```
> REDIS_CONTAINER_PATH=/home/redisuser/redis/
> ```
nit: could you add the comment before this that it should be sync with WORKDIR from Dockerfile.
___
*[utils/docker/run_local.sh, line 47 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvvO033zHsLX9ixnW1:-LzvvO033zHsLX9ixnW2:b-ruug6y) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L47)):*
> ```
> redis-6.0-fedora-31
> ```
nit:
redis-6-0
Let's say you use another dockerfile - the name will be inconsistent.
___
*[utils/docker/run_local.sh, line 51 at r1](https://reviewable.io/reviews/pmem/redis/123#-Lzvw75cAQUcfyoK5GZi:-Lzvw75cAQUcfyoK5GZj:bdsotg6) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L51)):*
> ```
> hpwdttp_proxy
> ```
http_proxy

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[utils/docker/docker_run_test.sh, line 26 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvujV756FaYsInfv-_:-Lzw-wxu-zbuoNkiOuHs:b-896fix) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/docker_run_test.sh#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> # docker_run_build.sh - is called inside a Docker container;
> # prepares and runs redis build for specified pull request number
> ```
nit:
docker_run_test.sh - is called inside a Docker container
run redis tests
</blockquote></details>

Done.
___
*[utils/docker/run_local.sh, line 27 at r1](https://reviewable.io/reviews/pmem/redis/123#-Lzvvi8f-56Ax83OpbXz:-Lzw0PTJB4k-NR5VwvHl:b-896fix) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L27)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> docker_run_build.sh
> ```
docker_run_test.sh
</blockquote></details>

Done.
___
*[utils/docker/run_local.sh, line 51 at r1](https://reviewable.io/reviews/pmem/redis/123#-Lzvw75cAQUcfyoK5GZi:-Lzw0a7g7Y7R-50YcfR0:b-896fix) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/run_local.sh#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> hpwdttp_proxy
> ```
http_proxy
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: 1 of 3 files reviewed, all discussions resolved

___
*[utils/docker/docker_run_test.sh, line 26 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvujV756FaYsInfv-_:-LzwDCShDMxU1Csx5raj:b1sv7t8) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/docker_run_test.sh#L26)):*
> ```
> prepares and runs redis build for specified pull request number
> ```
please update this to "run redis tests"

**Review by michalbiesek — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123#-:-LzwFgd4AfVyLeOs-E23:bb6ywmx)* status: 1 of 3 files reviewed, all discussions resolved

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: 1 of 3 files reviewed, all discussions resolved

___
*[utils/docker/docker_run_test.sh, line 26 at r1](https://reviewable.io/reviews/pmem/redis/123#-LzvujV756FaYsInfv-_:-LzwJ_rmDoIqZtWJEyhn:b-896fix) ([raw file](https://github.com/pmem/redis/blob/e49bbfc165c8391df1798bd94ad11cce3aaa504f/utils/docker/docker_run_test.sh#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> prepares and runs redis build for specified pull request number
> ```
please update this to "run redis tests"
</blockquote></details>

Done.

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[utils/docker/Dockerfile.fedora-31, line 47 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FM-eU81NLJaqlbLg0:-M-FM-eV2szZMmFXvSeN:bgbe5br) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/Dockerfile.fedora-31#L47)):*
> ```
> ENV MEMKIND_URL="http://download.opensuse.org/repositories/home:/mbiesek/Fedora_31/x86_64/memkind-1.10.0-2.2.x86_64.rpm"
> ENV MEMKIND_DEVEL_URL="http://download.opensuse.org/repositories/home:/mbiesek/Fedora_31/x86_64/memkind-devel-1.10.0-2.2.x86_64.rpm"
> RUN rpm -i --nosignature $MEMKIND_URL && rpm -i --nosignature $MEMKIND_DEVEL_URL
> ```

I think it can be installed via one command
___
*[utils/docker/docker_run_test.sh, line 27 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FMPS1BU-ZP63GGgnc:-M-FMPS1BU-ZP63GGgnd:bb7o4wd) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/docker_run_test.sh#L27)):*
> ```Shell
> #
> # docker_run_test.sh - is called inside a Docker container;
> # run redis tests
> ```

runs
___
*[utils/docker/run_local.sh, line 37 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FN4n93gWz4Bc-625u:-M-FN4n93gWz4Bc-625v:b9i8k8p) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/run_local.sh#L37)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> DOCKER_IMAGE_NAME="$1"
> 
> if [[ ! -f "$DOCKER_IMAGE_NAME" ]]; then
>     echo "Docker image "$DOCKER_IMAGE_NAME" does not exist."
>     exit 1
> fi
> ```
</details>

I personally think that for now it is overcomplicated since we have only one dockerfile

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta, @KFilipek, and @michalbiesek)

___
*[utils/docker/Dockerfile.fedora-31, line 47 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FM-eU81NLJaqlbLg0:-M0Wm9vEA6db4_mG6pcx:b-896fix) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/Dockerfile.fedora-31#L47)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

I think it can be installed via one command
</blockquote></details>

Done.
___
*[utils/docker/docker_run_test.sh, line 27 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FMPS1BU-ZP63GGgnc:-M0WmAZB0zigbhU_hshw:b-896fix) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/docker_run_test.sh#L27)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

runs
</blockquote></details>

Done.
___
*[utils/docker/run_local.sh, line 37 at r2](https://reviewable.io/reviews/pmem/redis/123#-M-FN4n93gWz4Bc-625u:-M0WmAydDSDHsSrgafJb:b-wex09) ([raw file](https://github.com/pmem/redis/blob/4181ea6161e0953c64c9eba17612efe48586fe6a/utils/docker/run_local.sh#L37)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> DOCKER_IMAGE_NAME="$1"
> 
> if [[ ! -f "$DOCKER_IMAGE_NAME" ]]; then
>     echo "Docker image "$DOCKER_IMAGE_NAME" does not exist."
>     exit 1
> fi
> ```
I personally think that for now it is overcomplicated since we have only one dockerfile
</blockquote></details>

Hardcoded the name of the Dockerfile.

**Review by picassogit — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123#-:-M10xJifCMMc3UrUJyof:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta)

**Comment by kasiawasiuta** [comment]
@KFilipek despite of GitHub blocking the merge, as I see everything is fixed and also Michal gave LGTM. Do you think you could merge this path?

**Review by KFilipek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/123)* status: all files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta)

**Pull request merged**
