### PR TITLE
Comparator for allocators

### PR DESCRIPTION
**Pull request by KFilipek**
Comparator implementation for alloc structure.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/74)

### CODE REVIEW

**Comment by michalbiesek** [comment]
___
*[src/alloc.h, line 80 at r1](https://reviewable.io/reviews/pmem/redis/74#-LIPR9NLEZj5phlB36lY:-LIPR9NLEZj5phlB36lZ:bahgk9y) ([raw file](https://github.com/pmem/redis/blob/40b0b243f9e2b93b71ec059572420d1f4375022f/src/alloc.h#L80)):*
> ```
> cmpAlloc
> ```
Cosmetics but consider rename. I saw in code function like for example: 
sdscmp,ziplistCompare,quicklistCompare which name begin from name of module, so here it could be maybe something like:
allocCompare, or alloccmp ?

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/74)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek and @karpiop)

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karpiop)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karpiop)

___
*[src/alloc.h, line 80 at r1](https://reviewable.io/reviews/pmem/redis/74#-LIPR9NLEZj5phlB36lY:-LIfqESP9pPAYnkApW_C:b-896fix) ([raw file](https://github.com/pmem/redis/blob/40b0b243f9e2b93b71ec059572420d1f4375022f/src/alloc.h#L80)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> cmpAlloc
> ```
Cosmetics but consider rename. I saw in code function like for example: 
sdscmp,ziplistCompare,quicklistCompare which name begin from name of module, so here it could be maybe something like:
allocCompare, or alloccmp ?
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karpiop)

**Review by michalbiesek — APPROVED** [review]

**Review by TomekIdczak97 — APPROVED** [review]
LGTM

**Pull request merged**
