### PR TITLE
Updated Readme with Redis build instructions.

### PR DESCRIPTION
**Pull request by kasiawasiuta**
Memkind build instructions added to Makefile.
Changed build scripts in memkind

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/26)

### CODE REVIEW

**Comment by KFilipek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/pmem/redis/26#-L96jelK71Eg68ShKJOG:-L96jelK71Eg68ShKJOH:b6o5jtv) ([raw file](https://github.com/pmem/redis/blob/60f05997c63b1aebdd183825bd5826c154c6c2af/README.md#L43)):*
> ```Markdown
>     % cd ../..
>     % export JE_PREFIX=je_
>     % ./autogen.sh; ./configure; make; make install
> ```

we don't need to do "make install" for Redis
Split last line into single commands.
When autogen fail, next will be executed failing  ./configure etc.

---

*[deps/Makefile, line 75 at r1](https://beta.reviewable.io/reviews/pmem/redis/26#-L96jnh_CzNSPbncyGdn:-L96jnh_CzNSPbncyGdo:b-6a28tz) ([raw file](https://github.com/pmem/redis/blob/c2bcf5e24a6fa283a6edc18ee041538e09329061/deps/Makefile#L75)):*
> ```Makefile
> .PHONY: lua
> 
> JEMALLOC_CFLAGS= -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops $(CFLAGS)
> ```

Add memkind build steps to makefile

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26)*

**Comment by kasiawasiuta** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/pmem/redis/26#-L96jelK71Eg68ShKJOG:-L9dWynx60OQsA-fAZQ3:b-tq0m4n) ([raw file](https://github.com/pmem/redis/blob/60f05997c63b1aebdd183825bd5826c154c6c2af/README.md#L43)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

we don't need to do "make install" for Redis
Split last line into single commands.
When autogen fail, next will be executed failing  ./configure etc.
</blockquote></details>

I moved it into the script, no make install inside :)

---

*[deps/Makefile, line 75 at r1](https://beta.reviewable.io/reviews/pmem/redis/26#-L96jnh_CzNSPbncyGdn:-L9je5GO72diteVzDXcL:b-896fix) ([raw file](https://github.com/pmem/redis/blob/c2bcf5e24a6fa283a6edc18ee041538e09329061/deps/Makefile#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Add memkind build steps to makefile
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26)*

**Comment by KFilipek** [comment]
Reviewed 2 of 4 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[deps/build-memkind.sh, line 36 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jhdgQ5nz-ni4Xw8dj:-L9jhdgQ5nz-ni4Xw8dk:b-jldteg) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L36)):*
> ```Shell
> if [ ! -f ./jemalloc/obj/lib/libjemalloc_pic.a ]; then
>         cd jemalloc
> 	test -e configure || autoconf
> ```

|| or &&?
&& will evaluate right side only if left will success.

---

*[deps/build-memkind.sh, line 52 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jhQiyC-Xs5ZSemXDj:-L9jhQiyC-Xs5ZSemXDk:b-pjew34) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L52)):*
> ```Shell
> 
> #use V=1 for full cmdlines of build
> make all -j $MAKEOPTS
> ```

Here is MAKEOPTS, but few lines up is nproc.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26)*

**Comment by KFilipek** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deps/build-memkind.sh, line 45 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jm2OkBveAmj4zjxp7:-L9jm2OkBveAmj4zjxp8:bik69lp) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L45)):*
> ```Shell
> fi
> 
> ./autogen.sh
> ```

Why autogen.sh run every time, but ./configure not

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26)*

**Comment by kasiawasiuta** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[deps/build-memkind.sh, line 36 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jhdgQ5nz-ni4Xw8dj:-LASM42zEI5MkoVKjHim:b-ni16zl) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L36)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

|| or &&?
&& will evaluate right side only if left will success.
</blockquote></details>

|| will evaluate only if left side is not a success so if configure file does not exist, run autoconf to generate it. This is what we want

---

*[deps/build-memkind.sh, line 45 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jm2OkBveAmj4zjxp7:-LASQR4TDo8huAPgkB0J:b-yayxw8) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L45)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why autogen.sh run every time, but ./configure not
</blockquote></details>

Autogen is generating configure and VERSION file. when cleaning, configure file stays bot the VERSION file was removed and it was crutial for further steps. So I removed the condition of checking if configure exists and instead put a condition for VERSION file

---

*[deps/build-memkind.sh, line 52 at r2](https://beta.reviewable.io/reviews/pmem/redis/26#-L9jhQiyC-Xs5ZSemXDj:-LAS_-3r5KANVOfwSWZd:bdtnsga) ([raw file](https://github.com/pmem/redis/blob/da86db9185d2c04c8c037a1f1858f733667cabbe/deps/build-memkind.sh#L52)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Here is MAKEOPTS, but few lines up is nproc.
</blockquote></details>

My bad, fixed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26)*

**Comment by KFilipek** [comment]
Last thing: when memkind is not installed in system it can't be compiled successfuly

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26#-:-LAT6GQO71xFPNGkrcOe:bffugx2)*

**Comment by kasiawasiuta** [comment]
done

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/26#-:-LATzc6w6LseSD9JIMoz:bb7f2mf)*

**Pull request merged**
