### PR TITLE
new version of memkind added

### PR DESCRIPTION
**Pull request by Laguland**
new version of memkind added. Last commit to memkind master: merge pull request # 136. 15.11.2018

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/79)

### CODE REVIEW

**Comment by KFilipek** [comment]
test this please

**Comment by michalbiesek** [comment]
Change commit message to refer to specified commit in memkind repository

**Comment by michalbiesek** [comment]
Split this PR to two commits:
-one refer to changes in deps
-second one to other changes in Redis code

**Comment by Laguland** [comment]
> Change commit message to refer to specified commit in memkind repository

Done.

> Split this PR to two commits:
> -one refer to changes in deps
> -second one to other changes in Redis code

Done.

**Comment by michalbiesek** [comment]
Regarding commit message, it would be more clear to refer directly to commit SHA hash.
Change first commit message, it should be something like:
Update memkind version 1.6.0 to 1.8.0 

-updated version was not yet officially released (commit f9bc6df77d8243ec5ba81f1a8c4528f96bd73c4a)

Regarding second commit message:
Rename defag_hint function

**Comment by michalbiesek** [comment]
@KFilipek 
I think ci/jenkins/redis job should be updated:
 to refer: "4.0-volatile_with_memkind_5.0" branch not: "4.0-volatile"

**Comment by michalbiesek** [comment]
@KFilipek 
You are more familiar with build script, should:

        redis/deps/build-memkind.sh
      
be updated ?

**Comment by michalbiesek** [comment]
@Laguland 
For example:
https://github.com/pmem/redis/blob/d0d0867e730998f3589b7933e968840a8e1e8db4/src/memkind_malloc.c#L49
Calling for jemk_malloc_usable_size(ptr); should be changed to calling memkind_malloc_usable_size

AFAIK 
There was a plan to refer only to memkind, this could be done by other PR, but I don't know if You aware of that.
Instead of using second jemalloc to you could use API like memkind_malloc(MEMKIND_DEFAULT,...)

**Pull request closed without merging**
