### PR TITLE
commands for lists handled with memkind

### PR DESCRIPTION
**Pull request by wojtuss**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/17)

### CODE REVIEW

**Comment by KFilipek** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/alloc.h, line 2 at r1](https://reviewable.io:443/reviews/pmem/redis/17#-L6MuTo9rksV23Oh7HPs:-L6MuToCldIiT8RhG8vx:b7ifd1z) ([raw file](https://github.com/pmem/redis/blob/742475f7f4a90db4b1710ae57b756b51f7b1f4eb/src/alloc.h#L2)):*
> ```objc
> /*
>  * Copyright (c) 201l, Intel Corporation
> ```

Change licence year

---

*[src/object.c, line 41 at r1](https://reviewable.io:443/reviews/pmem/redis/17#-L6N-1TOu3LBRIbQHDw0:-L6N-1TQ1wtiWNcO-NjL:b-58mdoh) ([raw file](https://github.com/pmem/redis/blob/742475f7f4a90db4b1710ae57b756b51f7b1f4eb/src/object.c#L41)):*
> ```C
> /* ===================== Creation and parsing of objects ==================== */
> 
> //robj *createObjectA(int type, void *ptr, alloc a) {
> ```

Please remove comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/17)*

**Comment by KFilipek** [comment]
Reviewed 12 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/17)*

**Comment by wojtuss** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/alloc.h, line 2 at r1](https://reviewable.io:443/reviews/pmem/redis/17#-L6MuTo9rksV23Oh7HPs:-L6N07JB4-JxYftIwJRN:b-896fix) ([raw file](https://github.com/pmem/redis/blob/742475f7f4a90db4b1710ae57b756b51f7b1f4eb/src/alloc.h#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Change licence year
</blockquote></details>

Done.

---

*[src/object.c, line 41 at r1](https://reviewable.io:443/reviews/pmem/redis/17#-L6N-1TOu3LBRIbQHDw0:-L6N085OWYzcy3NZiy09:b-896fix) ([raw file](https://github.com/pmem/redis/blob/742475f7f4a90db4b1710ae57b756b51f7b1f4eb/src/object.c#L41)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Please remove comments
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/17)*

**Comment by KFilipek** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/17)*

**Comment by KFilipek** [comment]
LGTM

**Comment by jschmieg** [comment]
Reviewed 9 of 12 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/17)*

**Pull request merged**
