### PR TITLE
Move SDS to PM

### PR DESCRIPTION
**Pull request by jschmieg**
Allocates new string in PM. Frees old strings from DRAM.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/124)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124)* status: all files reviewed, 4 unresolved discussions (waiting on @jschmieg and @kasiawasiuta)

___
*[src/object.c, line 507 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-AB-TK5gIT94StXxKj:-M-AB-TK5gIT94StXxKk:b86z1kk) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/object.c#L507)):*
> ```C
> 
> #ifdef USE_MEMKIND
>     if (server.pmem_str_mode && PMEM_STR_VAL) {
> ```

Checking bit flags should be with & instead of &&
___
*[src/sds.c, line 176 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-AB5Y6Cvv4K3g8yXwp:-M-AB5Y6Cvv4K3g8yXwq:bfju5ws) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L176)):*
> ```C
>     unsigned char *fp; /* flags pointer. */
> 
>     sh = zmalloc_pmem(hdrlen+initlen+1);
> ```

spaces around '+' (same below)
___
*[src/sds.c, line 177 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABDBK-jJQV4TUy2lc:-M-ABDBK-jJQV4TUy2ld:brt4p9h) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L177)):*
> ```C
> 
>     sh = zmalloc_pmem(hdrlen+initlen+1);
>     if (init==SDS_NOINIT)
> ```

spaces around "=="
___
*[src/sds.c, line 184 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABGeJ41fEcLUIjG9R:-M-ABGeJ41fEcLUIjG9S:b-ci1e21) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L184)):*
> ```C
>     s = (char*)sh+hdrlen;
>     fp = ((unsigned char*)s)-1;
>     switch(type) {
> ```

space after switch

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124)* status: all files reviewed, 5 unresolved discussions (waiting on @jschmieg and @kasiawasiuta)

___
*[src/sds.h, line 230 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABm1a5K2Ie-GTCCG7:-M-ABm1b6VxgKUOD1FGj:btxih1q) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.h#L230)):*
> ```
> sds sdsnewlenPM(const void *init, size_t initlen);
> ```
remove this from sds.h and make this function static

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta, @KFilipek, and @michalbiesek)

___
*[src/object.c, line 507 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-AB-TK5gIT94StXxKj:-M-ALAlI50Hk7xmK32F9:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/object.c#L507)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Checking bit flags should be with & instead of &&
</blockquote></details>

done
___
*[src/sds.h, line 230 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABm1a5K2Ie-GTCCG7:-M-ALDZfCOkOdsSLlzbb:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.h#L230)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sds sdsnewlenPM(const void *init, size_t initlen);
> ```
remove this from sds.h and make this function static
</blockquote></details>

done
___
*[src/sds.c, line 176 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-AB5Y6Cvv4K3g8yXwp:-M-ALF9FBQQlup8pTQJn:bbb85us) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L176)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

spaces around '+' (same below)
</blockquote></details>

I am following oryginal formatting (see sdsnewlen)
___
*[src/sds.c, line 177 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABDBK-jJQV4TUy2lc:-M-ALMkW2SC29m8vLGyd:bkw04gk) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L177)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

spaces around "=="
</blockquote></details>

I am following original formatting (see sdsnewlen)
___
*[src/sds.c, line 184 at r1](https://reviewable.io/reviews/pmem/redis/124#-M-ABGeJ41fEcLUIjG9R:-M-ALNO23fEiLpKt-2TM:bkw04gk) ([raw file](https://github.com/pmem/redis/blob/29da84fdd838ef964c462c6a0e132bf0de940a2c/src/sds.c#L184)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

space after switch
</blockquote></details>

I am following original formatting (see sdsnewlen)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/124#-:-M-AehWK-q7Xwv3BivGR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

**Pull request merged**
