### PR TITLE
Use variable multiplier in Ratio policy

### PR DESCRIPTION
**Pull request by jschmieg**
Variable multiplier which depends on distance to target ratio.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/171)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/171)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg)

___
*[src/pmem.c, line 82 at r1](https://reviewable.io/reviews/pmem/redis/171#-M4sVIyU3MQHAalZ0UpB:-M4sVIyU3MQHAalZ0UpC:b-twecpx) ([raw file](https://github.com/pmem/redis/blob/e7161abd8ab98a488cebbb3309b6bfb71eb3d2ad/src/pmem.c#L82)):*
> ```
> 5*variableMultipler*THRESHOLD_STEP
> ```
not strictly related with this PR, but could we change 5*THRESHOLD_STEP to one macro
something like:
THRESHOLD_STEP -> NORMAL_THRESHOLD_STEP
 5*THRESHOLD_STEP  -> AGGRESIVE_THRESHOLD_STEP
please don't stick with the name I just don't like read this double multiply

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/171)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/pmem.c, line 82 at r1](https://reviewable.io/reviews/pmem/redis/171#-M4sVIyU3MQHAalZ0UpB:-M51ZzCPChkPCwUT4QPL:b-896fix) ([raw file](https://github.com/pmem/redis/blob/e7161abd8ab98a488cebbb3309b6bfb71eb3d2ad/src/pmem.c#L82)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 5*variableMultipler*THRESHOLD_STEP
> ```
not strictly related with this PR, but could we change 5*THRESHOLD_STEP to one macro
something like:
THRESHOLD_STEP -> NORMAL_THRESHOLD_STEP
 5*THRESHOLD_STEP  -> AGGRESIVE_THRESHOLD_STEP
please don't stick with the name I just don't like read this double multiply 
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/171)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/171#-:-M51eKci2w95P0ZZGicr:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/171)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
