### PR TITLE
Create independent option for dictionary placement on PMEM

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/134)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg and @karpiop)

**Review by jschmieg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/134)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @karpiop, @KFilipek, and @michalbiesek)

___
*[redis.conf, line 1709 at r1](https://reviewable.io/reviews/pmem/redis/134#-M-Ug7re3zMuKWbG2Aqp:-M-Ug7re3zMuKWbG2Aqq:b-bm6qfe) ([raw file](https://github.com/pmem/redis/blob/c75bd35902b8dc89304c0cf151a5b29b2c7bfd79/redis.conf#L1709)):*
> ```
> # Determine if keys should be placed on Persistent memory
> keys-on-pmem no
> # Determine if dictionary should be placed on Persistent memory
> ```

Using "dictEntry" is less confusing

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/134)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @karpiop)

___
*[redis.conf, line 1709 at r1](https://reviewable.io/reviews/pmem/redis/134#-M-Ug7re3zMuKWbG2Aqp:-M-Uggm7AvVI9tUZFUYb:bntc320) ([raw file](https://github.com/pmem/redis/blob/c75bd35902b8dc89304c0cf151a5b29b2c7bfd79/redis.conf#L1709)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Using "dictEntry" is less confusing
</blockquote></details>

Please not use structure/function names outside source code. Maybe "dictionary metadata" or something else? 
If dictEntry and underlying structure is moved to PMEM "dictionary" is used in proper manner.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/134)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg, @karpiop, and @michalbiesek)

___
*[redis.conf, line 1709 at r3](https://reviewable.io/reviews/pmem/redis/134#-M-Uhsl26aZ2njXF2HUx:-M-Uhsl26aZ2njXF2HUy:b-abr0pb) ([raw file](https://github.com/pmem/redis/blob/baefc948f85e45ee9f772c0650735e5699c34bec/redis.conf#L1709)):*
> ```
> # Determine if keys should be placed on Persistent memory
> keys-on-pmem no
> # Determine if dict entires should be placed on Persistent memory
> ```

entires -> entries

Or maybe "entire dictionary"?

**Comment by michalbiesek** [comment]
Done via "dictionary entries"

**Review by jschmieg — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/134)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg, @karpiop, and @michalbiesek)

**Review by jschmieg — APPROVED** [review]

**Pull request merged**
