### PR TITLE
Modifies memset and memcpy enabling usage of PMDK allocator.

### PR DESCRIPTION
**Pull request by Laguland**
Modifies memset and memcpy enabling usage of PMDK allocator.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/80)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/80)* status: all files reviewed, 10 unresolved discussions (waiting on @Laguland and @kasiawasiuta)

___
*[src/cluster.c, line 2494 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0kIvE0s_GqwnhjlsT:-LU0kIvF14KEo3tF8MK8:b84h4t7) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/cluster.c#L2494)):*
> ```C
>     }
>     channel->a->memcpy(hdr->data.publish.msg.bulk_data,channel->ptr,sdslen(channel->ptr));
> 	channel->a->memcpy(hdr->data.publish.msg.bulk_data + sdslen(channel->ptr),
> ```

spaces instead of tabs
___
*[src/debug.c, line 144 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0kZnt0HDF2D1CI74K:-LU0kZnt0HDF2D1CI74L:b-frcgdx) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L144)):*
> ```C
>             key = dictGetKey(de);
>             keyobj = createStringObject(key,sdslen(key));
> 			keyobj->a->memset(digest, 0, 20); /* This key-val digest */
> ```

Now you are changing logic of program, you can leave as before
___
*[src/debug.c, line 194 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0knfm6RGeEpeWLUMi:-LU0knfm6RGeEpeWLUMj:b-3p6c4g) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L194)):*
> ```C
>                         score = zzlGetScore(sptr);
> 
>                         o->a->memset(eledigest,0,20);
> ```

eledigest wasn't allocated by external allocator, please revert it
___
*[src/debug.c, line 217 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0krkO2LaKkxnVbVLE:-LU0krkO2LaKkxnVbVLF:b-3p6c4g) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L217)):*
> ```C
> 
>                         snprintf(buf,sizeof(buf),"%.17g",*score);
>                         o->a->memset(eledigest,0,20);
> ```

eledigest wasn't allocated by external allocator, please revert it
___
*[src/evict.c, line 175 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0l9aN5-PvgAmbvGNf:-LU0l9aN5-PvgAmbvGNg:b331dkv) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/evict.c#L175)):*
> ```C
>         de = samples[j];
>         key = dictGetKey(de);
> 		
> ```

remove unnecessary tabs
___
*[src/hyperloglog.c, line 1421 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0lDqvCfmjWp909jVO:-LU0lDqvCfmjWp909jVP:b-l3bgdg) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/hyperloglog.c#L1421)):*
> ```C
>      * time also verifying that the computed cardinality is the same. */
>     o = createHLLObject();
> 	o->a->memset(hdr->registers, 0, HLL_DENSE_SIZE - HLL_HDR_SIZE);
> ```

don't change the logic, leave as before
___
*[src/rdb.c, line 1605 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0lzg2EMkk-brO_INq:-LU0lzg2EMkk-brO_INr:bz5o5w1) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/rdb.c#L1605)):*
> ```C
>             } else if (!strcasecmp(auxkey->ptr,"repl-id")) {
>                 if (rsi && sdslen(auxval->ptr) == CONFIG_RUN_ID_SIZE) {
>                     auxval->a->memcpy(rsi->repl_id,auxval->ptr,CONFIG_RUN_ID_SIZE+1);
> ```

Don't change rdb files, please revert it
___
*[src/scripting.c, line 420 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0m3Zb9GvjJkFp9jy7:-LU0m3Zb9GvjJkFp9jy8:b-81upoe) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/scripting.c#L420)):*
> ```C
>             argv[j] = cached_objects[j];
>             cached_objects[j] = NULL;
>             argv[j]->a->memcpy(s,obj_s,obj_len+1);
> ```

revert it
___
*[src/sort.c, line 104 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0m9gv5-TtLCmxaAsF:-LU0m9gv5-TtLCmxaAsG:b-pi9imj) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/sort.c#L104)):*
> ```C
>     k = keyobj->ptr;
>     subst->a->memcpy(k,spat,prefixlen);
> 	subst->a->memcpy(k+prefixlen,ssub,sublen);
> ```

remove tabs
___
*[src/sort.c, line 105 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0mB-V0qwUjnbpxMbA:-LU0mB-V0qwUjnbpxMbB:b-pi9imj) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/sort.c#L105)):*
> ```C
>     subst->a->memcpy(k,spat,prefixlen);
> 	subst->a->memcpy(k+prefixlen,ssub,sublen);
> 	subst->a->memcpy(k+prefixlen+sublen,p+1,postfixlen);
> ```

remove tabs

**Review by Laguland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/80)* status: 8 of 12 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @kasiawasiuta)

___
*[src/cluster.c, line 2494 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0kIvE0s_GqwnhjlsT:-LU53DnlCG-_RLlvQMM2:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/cluster.c#L2494)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

spaces instead of tabs
</blockquote></details>

Done.
___
*[src/debug.c, line 144 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0kZnt0HDF2D1CI74K:-LU53F5ZAV5QhX-JCZPL:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L144)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Now you are changing logic of program, you can leave as before
</blockquote></details>

Done.
___
*[src/debug.c, line 194 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0knfm6RGeEpeWLUMi:-LU53GFFErYgTXCmCvVE:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L194)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

eledigest wasn't allocated by external allocator, please revert it
</blockquote></details>

Done.
___
*[src/debug.c, line 217 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0krkO2LaKkxnVbVLE:-LU53G_Z0dfKE9w5yf35:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/debug.c#L217)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

eledigest wasn't allocated by external allocator, please revert it
</blockquote></details>

Done.
___
*[src/hyperloglog.c, line 1421 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0lDqvCfmjWp909jVO:-LU53IES4UPZnN8n0lXM:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/hyperloglog.c#L1421)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

don't change the logic, leave as before
</blockquote></details>

Done.
___
*[src/sort.c, line 104 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0m9gv5-TtLCmxaAsF:-LU53JdcB6mXQ8G_8PfW:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/sort.c#L104)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove tabs
</blockquote></details>

Done.
___
*[src/sort.c, line 105 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0mB-V0qwUjnbpxMbA:-LU53Jzr9OxZq5iDwrPj:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/sort.c#L105)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove tabs
</blockquote></details>

Done.
___
*[src/evict.c, line 175 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0l9aN5-PvgAmbvGNf:-LU53LVR3r8aPFuRNesJ:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/evict.c#L175)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove unnecessary tabs
</blockquote></details>

Done.
___
*[src/rdb.c, line 1605 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0lzg2EMkk-brO_INq:-LU53Mka8aryERUQsmlX:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/rdb.c#L1605)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Don't change rdb files, please revert it
</blockquote></details>

Done.
___
*[src/scripting.c, line 420 at r1](https://reviewable.io/reviews/pmem/redis/80#-LU0m3Zb9GvjJkFp9jy7:-LU53Nmp-zNK-1Rh_tNv:b-896fix) ([raw file](https://github.com/pmem/redis/blob/25fdaddfb3e908cad2ebf089669f0d5af6a7f86d/src/scripting.c#L420)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

revert it
</blockquote></details>

Done.

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/80)* status: 8 of 12 files reviewed, 13 unresolved discussions (waiting on @KFilipek and @Laguland)

___
*[src/debug.c, line 232 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCdFVs7fI1Kph_HvzX:-LVCdFVtCP9YfpL5SmoD:bfmf2ae) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/debug.c#L232)):*
> ```C
>                     sds sdsele;
> 
>                     o->a->memset(eledigest,0,20);
> ```

Please revert it
___
*[src/hyperloglog.c, line 831 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCfN9nA57Ad2MuSTkJ:-LVCfN9o744jVXBixQZL:b-81upoe) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/hyperloglog.c#L831)):*
> ```C
>      if (deltalen && next) memmove(next+deltalen,next,end-next);
>      sdsIncrLen(o->ptr,deltalen);
>      o->a->memcpy(p,seq,seqlen);
> ```

revert it
___
*[src/hyperloglog.c, line 1127 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCfP3cAdRiylTNYPga:-LVCfP3cAdRiylTNYPgb:b-81upoe) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/hyperloglog.c#L1127)):*
> ```C
>     o = createObject(OBJ_STRING,s);
>     hdr = o->ptr;
>     o->a->memcpy(hdr->magic,"HYLL",4);
> ```

revert it

**Review by Laguland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/80)* status: 8 of 11 files reviewed, 13 unresolved discussions (waiting on @KFilipek and @kasiawasiuta)

___
*[src/debug.c, line 232 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCdFVs7fI1Kph_HvzX:-LVbP3vT9U-jJCYprPet:b-896fix) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/debug.c#L232)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Please revert it
</blockquote></details>

Done.
___
*[src/hyperloglog.c, line 831 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCfN9nA57Ad2MuSTkJ:-LVbP4yB6yX64Md1w6-J:b-896fix) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/hyperloglog.c#L831)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

revert it
</blockquote></details>

Done.
___
*[src/hyperloglog.c, line 1127 at r2](https://reviewable.io/reviews/pmem/redis/80#-LVCfP3cAdRiylTNYPga:-LVbP5wf8H34NlzduTC8:b-896fix) ([raw file](https://github.com/pmem/redis/blob/27103d3194f1a3b7b0202474530dd619beb8d809/src/hyperloglog.c#L1127)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

revert it
</blockquote></details>

Done.

**Pull request closed without merging**
