### PR TITLE
Move Key to PM

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/127)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @kasiawasiuta)

___
*[src/sds.c, line 245 at r1](https://reviewable.io/reviews/pmem/redis/127#-M-FD8rWCT2TOcemytCp:-M-FD8rWCT2TOcemytCq:b-r1o7m9) ([raw file](https://github.com/pmem/redis/blob/c98fef1dcf1850e8d61daab515fde075507ad3fa/src/sds.c#L245)):*
> ```
> #define UNUSED(x) (void)(x)
> ```
I suggest move this existing line above your definition and use it here, same in moveSdsToPM(sds s)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @kasiawasiuta)

___
*[src/sds.c, line 245 at r1](https://reviewable.io/reviews/pmem/redis/127#-M-FF33h7zGLVyIgcYIF:-M-FF33h7zGLVyIgcYIG:bj88kzb) ([raw file](https://github.com/pmem/redis/blob/c98fef1dcf1850e8d61daab515fde075507ad3fa/src/sds.c#L245)):*
> ```C
> 
> sds sdsdupPM(const sds s) {
>     (void)s;
> ```

Use to avoid warning: 
(void)(s)

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

___
*[src/db.c, line 181 at r2](https://reviewable.io/reviews/pmem/redis/127#-M-FMKBX04fUiMH1Y4PI:-M-FMKBX04fUiMH1Y4PJ:b-m3d577) ([raw file](https://github.com/pmem/redis/blob/7ae7b8a672f6e774e1a08faf692dd515845c5657/src/db.c#L181)):*
> ```
> PMEM_STR_VAL_KEY
> ```
LGTM, but I would wait for #130 to use it here

**Comment by KFilipek** [comment]
Sure

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127#-:-M-FYkPb8hliESjFqqQN:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @kasiawasiuta and @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

**Pull request merged**
