### PR TITLE
Allocate and free client argv always from DRAM

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/176)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/176)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jschmieg)

___
*[src/networking.c, line 1150 at r1](https://reviewable.io/reviews/pmem/redis/176#-M5QlPWa8lYC22eeF3Ds:-M5QlPWa8lYC22eeF3Dt:byzwsw7) ([raw file](https://github.com/pmem/redis/blob/11bb613245779530a8f1a99c71fd3335911faa46/src/networking.c#L1150)):*
> ```C
>     /* Release other dynamically allocated client structure fields,
>      * and finally release the client structure itself. */
>     if (c->name) decrRefCount(c->name);
> ```

https://github.com/pmem/redis/blob/11bb613245779530a8f1a99c71fd3335911faa46/src/networking.c#L2509 zrealloc_dram ?
I am aware that we don't have such a function exposed and this would required a change :)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/176)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jschmieg)

___
*[src/networking.c, line 2486 at r1](https://reviewable.io/reviews/pmem/redis/176#-M6APq704AtHkU9-hMZd:-M6APq713ozUPX8V-vll:bjdfx95) ([raw file](https://github.com/pmem/redis/blob/11bb613245779530a8f1a99c71fd3335911faa46/src/networking.c#L2486)):*
> ```
> freeClientArgv
> ```
If you include changes from #184 you could replace 
https://github.com/pmem/redis/blob/90d9ed375ff143ac01d43116dab293f25bc49af3/src/networking.c#L958
with decrRefCountDRAM

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/176)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jschmieg and @michalbiesek)

___
*[src/networking.c, line 1150 at r1](https://reviewable.io/reviews/pmem/redis/176#-M5QlPWa8lYC22eeF3Ds:-M6d4-rC8I6-dHd0VVZ5:b-896fix) ([raw file](https://github.com/pmem/redis/blob/11bb613245779530a8f1a99c71fd3335911faa46/src/networking.c#L1150)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

https://github.com/pmem/redis/blob/11bb613245779530a8f1a99c71fd3335911faa46/src/networking.c#L2509 zrealloc_dram ?
I am aware that we don't have such a function exposed and this would required a change :)
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/176#-:-M6iS5br0pNDGIc8tiza:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
