### PR TITLE
Dict hash in dram

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/162)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/162)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg)

___
*[src/dict.c, line 224 at r1](https://reviewable.io/reviews/pmem/redis/162#-M4xuAsJ43vLmqhoDa4U:-M4xuAsJ43vLmqhoDa4V:blzfj0c) ([raw file](https://github.com/pmem/redis/blob/143b59f15a4126ef29105714d2be94ec6d2b2506/src/dict.c#L224)):*
> ```C
>         zfree_dram(d->ht[0].table);
>         d->ht[0] = d->ht[1];
>         _dictReset(&d->ht[1]);
> ```

What about:
https://github.com/pmem/redis/blob/555481cf0b10300d7386545431d94584f1ee0642/src/dict.c#L462

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/162)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/dict.c, line 224 at r1](https://reviewable.io/reviews/pmem/redis/162#-M4xuAsJ43vLmqhoDa4U:-M6ZF1Cm3tHzNrZ1Locj:b-896fix) ([raw file](https://github.com/pmem/redis/blob/143b59f15a4126ef29105714d2be94ec6d2b2506/src/dict.c#L224)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

What about:
https://github.com/pmem/redis/blob/555481cf0b10300d7386545431d94584f1ee0642/src/dict.c#L462

</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/162)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/162#-:-M6ZN9R_1qmX0tMX-nF1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
