### PR TITLE
Fix default Redis compilation w/o Memkind

### LINKED ISSUE #107: Compilation fails with 5.0-poc_cow
```
git clone https://github.com/pmem/redis.git
git checkout 5.0-poc_cow
make
-> fail: linker don't see symbol zmalloc_pmem
```

### PR DESCRIPTION
**Pull request by KFilipek**
This PR fixes default building of Redis 5.0-poc_cow.

Fixes #107

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/109)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/109)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta, @KFilipek, and @michalbiesek)

___
*[src/object.c, line 134 at r1](https://reviewable.io/reviews/pmem/redis/109#-Lb2keAm9ViK00Dvs7s5:-Lb2keAm9ViK00Dvs7s6:b-x958gb) ([raw file](https://github.com/pmem/redis/blob/48ca1ea47b414ef727fb663416224a9bc9a3926b/src/object.c#L134)):*
> ```
> createRawStringObjectPM(ptr,len);
> ```
It's not strictly related with this PR, but you could call here  directly
createObject(OBJ_STRING, sdsnewlenPM(ptr,len));
And remove completely function *createRawStringObjectPM(const char *ptr, size_t len) but it's up to you

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/109)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta and @KFilipek)

**Review by kasiawasiuta — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/109#-:-Lb2sAV56j0a0o5mN8mx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/109)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/object.c, line 134 at r1](https://reviewable.io/reviews/pmem/redis/109#-Lb2keAm9ViK00Dvs7s5:-Lb2sI2B7S3shfbRzwSD:b-kswty9) ([raw file](https://github.com/pmem/redis/blob/48ca1ea47b414ef727fb663416224a9bc9a3926b/src/object.c#L134)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> createRawStringObjectPM(ptr,len);
> ```
It's not strictly related with this PR, but you could call here  directly
createObject(OBJ_STRING, sdsnewlenPM(ptr,len));
And remove completely function *createRawStringObjectPM(const char *ptr, size_t len) but it's up to you
</blockquote></details>

Thanks, so I will discuss this suggestion separately

**Pull request merged**
