### PR TITLE
Geo fix - allocator mismatch

### PR DESCRIPTION
**Pull request by KFilipek**
found bug which cause stuck on geo tests. Geo should be stored in RAM, so I modified code to avoid creating objects by Memkind allocator.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/73)

### CODE REVIEW

**Comment by michalbiesek** [comment]
___
*[src/t_zset.c, line 1577 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFS-tW9bgJ4pl5DBl9:-LIFS-tW9bgJ4pl5DBlA:bqyiy9e) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/t_zset.c#L1577)):*
> ```
> zsetAddA(zobj, score, ele, &retflags, &newscore,a);
> ```
zsetAddA(zobj, score, ele, &retflags, &newscore, a);
Add space before last argument

**Comment by michalbiesek** [comment]
___
*[src/t_zset.c, line 1608 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFSQyd9n3VyWeM3nX2:-LIFSQyd9n3VyWeM3nX3:b-uhaxe8) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/t_zset.c#L1608)):*
> ```
> zaddCommand
> ```
Rename to zaddCommandM ?

**Comment by michalbiesek** [comment]
___
*[src/t_zset.c, line 1612 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFSW7LA4_OO_t9s4l0:-LIFSW7M8IYZYMpATOku:b9ekgo6) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/t_zset.c#L1612)):*
> ```
> zincrbyCommand
> ```
Rename to zincrbyCommandM ?

**Comment by michalbiesek** [comment]
___
*[src/server.h, line 2110 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFTDlrApxPEMS56IG_:-LIFTDlrApxPEMS56IGa:b-xrfcfz) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/server.h#L2110)):*
> ```
> zaddGenericCommand(c,ZADD_NONE,z_alloc)
> ```
Maybe instead zaddGenericCommand here, it is better idea to have instead of it functions: 
*zaddCommand ( which is already present) 
*zaddCommandM.

zaddCommand would call zaddGenericCommand(c,ZADD_NONE,z_alloc);
zaddCommandM would call zaddGenericCommand(c,ZADD_NONE,m_alloc);

If You pick up this solution You could revert Your changes in geo.c

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/73)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @KFilipek)

___
*[src/t_zset.c, line 1577 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFS-tW9bgJ4pl5DBl9:-LIFiBAU920FKK2EXp1Q:b-896fix) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/t_zset.c#L1577)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> zsetAddA(zobj, score, ele, &retflags, &newscore,a);
> ```
zsetAddA(zobj, score, ele, &retflags, &newscore, a);
Add space before last argument
</blockquote></details>

Done.
___
*[src/t_zset.c, line 1608 at r1](https://reviewable.io/reviews/pmem/redis/73#-LIFSQyd9n3VyWeM3nX2:-LIFiW409yqgc0UuxCj5:byfmmz5) ([raw file](https://github.com/pmem/redis/blob/71d61af3c9df12a3784c86eb1a33c955cc75cf26/src/t_zset.c#L1608)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> zaddCommand
> ```
Rename to zaddCommandM ?
</blockquote></details>

Previously we don't change API, If I change this I should also rename almost every API function to be consistent

**Comment by michalbiesek** [comment]
___
*[src/t_zset.c, line 1613 at r3](https://reviewable.io/reviews/pmem/redis/73#-LIG_4MeD8tv3tkk1j1P:-LIG_4MeD8tv3tkk1j1Q:b-65pcli) ([raw file](https://github.com/pmem/redis/blob/ad46861bd3d7824c23097149e1d175686d404083/src/t_zset.c#L1613)):*
> ```
> zaddGenericCommand(c, ZADD_NONE,z_alloc);
> ```
Cosmetics:
I know there is no rules regarding style, but please do it with the same style, as function above ( remove spaces), to be precise:
zaddGenericCommand(c,ZADD_NONE,z_alloc);

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/73)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/t_zset.c, line 1613 at r3](https://reviewable.io/reviews/pmem/redis/73#-LIG_4MeD8tv3tkk1j1P:-LIGdrJxAs3EQDMXKkou:b-896fix) ([raw file](https://github.com/pmem/redis/blob/ad46861bd3d7824c23097149e1d175686d404083/src/t_zset.c#L1613)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> zaddGenericCommand(c, ZADD_NONE,z_alloc);
> ```
Cosmetics:
I know there is no rules regarding style, but please do it with the same style, as function above ( remove spaces), to be precise:
zaddGenericCommand(c,ZADD_NONE,z_alloc);
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/73#-:-LIGdybwA6S7bt7LcVmf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — APPROVED** [review]

**Review by TomekIdczak97 — APPROVED** [review]
LGTM

**Pull request merged**
