### PR TITLE
Changed tests script to ommit files specified in test.conf

### PR DESCRIPTION
**Pull request by kasiawasiuta**
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/18)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_helper.tcl, line 79 at r1](https://reviewable.io:443/reviews/pmem/redis/18#-L7a3e6q2lnMuEgqweZ3:-L7a3e6q2lnMuEgqweZ4:bsz5aon) ([raw file](https://github.com/pmem/redis/blob/83cdc5669f4001c08e77f67c90a205e20330224a/tests/test_helper.tcl#L79)):*
> ```Tcl
> set ::accurate 0; # If true runs fuzz tests with more iterations
> set ::force_failure 0
> set ::timeout 60; # 10 minutes without progresses will quit the test.
> ```

1 minute?

---

*[tests/test_helper.tcl, line 334 at r1](https://reviewable.io:443/reviews/pmem/redis/18#-L7a3lhruFOWsIuBaGs9:-L7a3lhruFOWsIuBaGsA:b-h4cx1m) ([raw file](https://github.com/pmem/redis/blob/83cdc5669f4001c08e77f67c90a205e20330224a/tests/test_helper.tcl#L334)):*
> ```Tcl
> 
>     # New unit to process?
>     if {
> ```

pls, unify indentation - either tabs or spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/18)*

**Comment by krzycz** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/18)*

**Comment by kasiawasiuta** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_helper.tcl, line 79 at r1](https://reviewable.io:443/reviews/pmem/redis/18#-L7a3e6q2lnMuEgqweZ3:-L7yMDhWpGCrcp8RJ65I:b-k9ojit) ([raw file](https://github.com/pmem/redis/blob/83cdc5669f4001c08e77f67c90a205e20330224a/tests/test_helper.tcl#L79)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

1 minute?
</blockquote></details>

Reverted to 10 minutes

---

*[tests/test_helper.tcl, line 334 at r1](https://reviewable.io:443/reviews/pmem/redis/18#-L7a3lhruFOWsIuBaGs9:-L7yMKRuPkcMk_UBvdjf:b-896fix) ([raw file](https://github.com/pmem/redis/blob/83cdc5669f4001c08e77f67c90a205e20330224a/tests/test_helper.tcl#L334)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

pls, unify indentation - either tabs or spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/18)*

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/18)*

**Comment by jschmieg** [comment]
:lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/redis/18#-:-L8XXZ1C9U-gJPZnUudb:bnfp4nl)*

**Comment by jschmieg** [comment]
Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/redis/18)*

**Pull request merged**
