### PR TITLE
Updated Fedora29 Dockerfile to link Redis with Memkind-1.9

### PR DESCRIPTION
**Pull request by kasiawasiuta**
Simplified memkind installation in the system, using memkind 1.9 release rpm packages.
Removed unnecessary build packages.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/redis/116)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/116#-:-LcVT4rn6-vhJMZnI5oC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/116)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

___
*[utils/docker/Dockerfile.fedora-29, line 37 at r1](https://reviewable.io/reviews/pmem/redis/116#-LcVRqpZ0nlZy6jb9igZ:-LcVRqpZ0nlZy6jb9ig_:bkju73w) ([raw file](https://github.com/pmem/redis/blob/bdd6c9b32cb0c00f22c81d8414c32b3132541141/utils/docker/Dockerfile.fedora-29#L37)):*
> ```
> # Install memkind
> # TODO: Change url to fedora-29 rpm after memkind official release
> ```

Install memkind from official release with packages delivered by https://build.opensuse.org/

Feel free to comment as you like, but please remove this TODO remark :)

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/116)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @michalbiesek)

___
*[utils/docker/Dockerfile.fedora-29, line 37 at r1](https://reviewable.io/reviews/pmem/redis/116#-LcVRqpZ0nlZy6jb9igZ:-Ld7yMobEK1XbYSNlomH:bmfxgaw) ([raw file](https://github.com/pmem/redis/blob/bdd6c9b32cb0c00f22c81d8414c32b3132541141/utils/docker/Dockerfile.fedora-29#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> # Install memkind
> # TODO: Change url to fedora-29 rpm after memkind official release
> ```

Install memkind from official release with packages delivered by https://build.opensuse.org/

Feel free to comment as you like, but please remove this TODO remark :)
</blockquote></details>

Done :)

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/116#-:-Ld7zF-88ZOCnI8COmQL:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
